import { useState, useEffect } from 'react';
import type { CandidateCondition } from '../lib/candidates';
import { createDTP, type ReferenceRange } from '../lib/ontomorph';

type Props = {
  condition: CandidateCondition;
  patientAge?: number;
  patientSex?: string;
};

export function MonitoringPlan({ condition, patientAge = 38, patientSex = 'male' }: Props) {
  const [ranges, setRanges] = useState<Record<string, ReferenceRange | null>>({});
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const dtp = createDTP();
    const fetchRanges = async () => {
      const results: Record<string, ReferenceRange | null> = {};
      for (const signal of condition.monitoringSignals) {
        results[signal.loincCode] = await dtp.holon.referenceRanges.getByLoincCode(
          signal.loincCode,
          patientAge,
          patientSex
        );
      }
      setRanges(results);
      setLoading(false);
    };
    fetchRanges();
  }, [condition, patientAge, patientSex]);

  const getShareText = () => {
    const lines = [
      `🩺 Constellation — Monitoring Plan for ${condition.name}`,
      '',
      `Condition: ${condition.name} (${condition.id})`,
      `${condition.description}`,
      '',
      'Recommended monitoring:',
      ...condition.monitoringSignals.map((s) => {
        const range = ranges[s.loincCode];
        return `• ${s.label} (LOINC ${s.loincCode})${range ? ` — Normal: ${range.low}–${range.high} ${range.unit}` : ''}`;
      }),
      '',
      'Generated by Constellation',
    ];
    return lines.join('\n');
  };

  const handleWhatsAppShare = () => {
    const text = encodeURIComponent(getShareText());
    window.open(`https://wa.me/?text=${text}`, '_blank');
  };

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between gap-2">
        <h4 className="font-display font-semibold text-sm text-text-primary">
          Recommended Tests to Confirm
        </h4>
        <button
          onClick={handleWhatsAppShare}
          className="min-h-[44px] px-3.5 flex items-center gap-1.5 rounded-xl bg-signal-dim text-signal text-xs font-medium hover:bg-signal/20 transition-colors active:scale-95 flex-shrink-0"
          aria-label="Share monitoring plan via WhatsApp"
        >
          <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor">
            <path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347z"/>
            <path d="M12 0C5.373 0 0 5.373 0 12c0 2.625.846 5.059 2.284 7.034L.789 23.49a.75.75 0 00.917.918l4.457-1.495A11.94 11.94 0 0012 24c6.627 0 12-5.373 12-12S18.627 0 12 0zm0 22c-2.319 0-4.476-.67-6.31-1.823l-.44-.262-2.647.887.888-2.648-.262-.44A9.96 9.96 0 012 12C2 6.486 6.486 2 12 2s10 4.486 10 10-4.486 10-10 10z"/>
          </svg>
          Share
        </button>
      </div>

      {/* Mobile Stacked Card View (<=640px) */}
      <div className="block sm:hidden space-y-2">
        {condition.monitoringSignals.map((signal) => {
          const range = ranges[signal.loincCode];
          return (
            <div
              key={`mob-${signal.loincCode}`}
              className="p-3 rounded-xl bg-surface border border-hairline space-y-1 text-xs"
            >
              <div className="flex items-center justify-between">
                <span className="font-medium text-text-primary">{signal.label}</span>
                <span className="font-mono text-[10px] text-signal bg-signal-dim/30 px-2 py-0.5 rounded">
                  {signal.loincCode}
                </span>
              </div>
              <div className="flex items-center justify-between text-text-muted pt-1 border-t border-hairline/30">
                <span>Normal Range:</span>
                {loading ? (
                  <span className="animate-pulse">Loading...</span>
                ) : range ? (
                  <span className="font-mono text-text-primary font-medium">
                    {range.low}–{range.high} {range.unit}
                  </span>
                ) : (
                  <span className="font-mono">{signal.unit}</span>
                )}
              </div>
            </div>
          );
        })}
      </div>

      {/* Desktop Table (>640px) */}
      <div className="hidden sm:block overflow-x-auto">
        <table className="w-full text-sm">
          <thead>
            <tr className="border-b border-hairline">
              <th className="text-left py-2 pr-4 font-medium text-text-muted text-xs uppercase tracking-wider">Test</th>
              <th className="text-left py-2 pr-4 font-medium text-text-muted text-xs uppercase tracking-wider">Code</th>
              <th className="text-left py-2 pr-4 font-medium text-text-muted text-xs uppercase tracking-wider">Normal Range</th>
              <th className="text-left py-2 font-medium text-text-muted text-xs uppercase tracking-wider">Unit</th>
            </tr>
          </thead>
          <tbody>
            {condition.monitoringSignals.map((signal) => {
              const range = ranges[signal.loincCode];
              return (
                <tr key={signal.loincCode} className="border-b border-hairline/50">
                  <td className="py-2.5 pr-4 text-text-primary">{signal.label}</td>
                  <td className="py-2.5 pr-4">
                    <span className="font-mono text-xs text-signal">{signal.loincCode}</span>
                  </td>
                  <td className="py-2.5 pr-4">
                    {loading ? (
                      <span className="text-text-muted animate-pulse">Loading...</span>
                    ) : range ? (
                      <span className="font-mono text-text-primary">
                        {range.low}–{range.high}
                      </span>
                    ) : (
                      <span className="text-text-muted">—</span>
                    )}
                  </td>
                  <td className="py-2.5">
                    <span className="font-mono text-xs text-text-muted">{range?.unit || signal.unit}</span>
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>

      <p className="text-xs text-text-muted">
        Normal ranges are adjusted for the patient's age and sex.
        Always verify with your local lab's standards.
      </p>
    </div>
  );
}
